import * as z from 'zod';

export const EventFormSchema = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  eventType: z.string().optional(),
  eventCategory: z.string().optional(),
  eventSubCategory: z.string().optional(),
  eventBudget: z.string().optional(),
  proposalDueDate: z.string().optional(),
  eventStartDate: z.string().optional(),
  eventEndDate: z.string().optional(),
  audienceSize: z.string().optional(),
  address: z.object({
    venueName: z.string().optional(),
    venueAddress: z.string().optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    zipCode: z.string().optional(),
  }),
  roomCount: z.number().optional(),
  generalSessionCount: z.number().optional(),
  breakoutSessionCount: z.number().optional(),
  presenterCount: z.number().optional(),
  microphones: z.object({
    wiredHandheld: z.number().optional(),
    wirelessHandheld: z.number().optional(),
    wirelessLavalier: z.number().optional(),
    headsetMicrophone: z.number().optional(),
    earsetMicrophone: z.number().optional(),
    gooseneckMicrophone: z.number().optional(),
    boundaryMicrophone: z.number().optional(),
    audienceMicrophone: z.number().optional(),
  }),
  speakers: z.object({
    speakers_8_15: z.number().optional(),
    line_array_speaker_system: z.number().optional(),
    subwoofer_12_18: z.number().optional(),
    reference_speaker_monitors: z.number().optional(),
    bluetooth_speaker_small: z.number().optional(),
    bluetooth_speaker_large: z.number().optional(),
    computer_audio_speaker_system: z.number().optional(),
    audio_rigging_and_truss: z.number().optional(),
  }),
  mixers: z.object({
    analog_mixer: z.number().optional(),
    digital_mixer: z.number().optional(),
    computer_audio_interface: z.number().optional(),
    multi_media_DI_box: z.number().optional(),
    broadcast_phone_line_interface: z.number().optional(),
    digital_audio_recording: z.number().optional(),
    audio_playback_instant_replay: z.number().optional(),
    cd_player: z.number().optional(),
    audio_processing: z.number().optional(),
  }),
  communication: z.object({
    wireless_belt_pack_and_headset: z.number().optional(),
    wired_belt_pack_and_headset: z.number().optional(),
  }),
  screens: z.record(z.number().optional()),
  projection: z.record(z.number().optional()),
  videoCamera: z.record(z.number().optional()),
  videoProcessing: z.record(z.number().optional()),
  presenterTools: z.record(z.number().optional()),
  lighting: z.record(z.number().optional()),
  scenic: z.record(z.number().optional()),
  electrical: z.record(z.number().optional()),
  staff: z.record(z.number().optional()),
  otherRequirements: z.record(z.number().optional()),
  comments: z.object({
    description: z.string().optional(),
  }),
});

export type EventFormFormValues = z.infer<typeof EventFormSchema>;
