const mongoose = require('mongoose');
const subscriptionSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  },
  plan: {
    id: String,
    object: String,
    active: Boolean,
    aggregate_usage: String,
    amount: Number,
    amount_decimal: String,
    billing_scheme: String,
    created: Number,
    currency: String,
    interval: String,
    interval_count: Number,
    livemode: Boolean,
    metadata: Object,
    nickname: String,
    product: String,
    tiers_mode: String,
    transform_usage: String,
    trial_period_days: Number,
    usage_type: String,
  },
  startDate: Date,
  endDate: Date,
  customerId: String,
  stripeSubscriptionId: String,
  billingCycleAnchor: Number,
  currentPeriodEnd: Date,
  currentPeriodStart: Date,
  collectionMethod: String,
  currency: String,
  customer: String,
  defaultTaxRates: Array,
  latestInvoice: Object,
  livemode: Boolean,
  nextPendingInvoiceItemInvoice: String,
  quantity: Number,
  status: String,
  latestInvoiceId: String,
  latestInvoiceUrl: String,
  latestInvoicePdf: String,
  // Add more fields as needed
});

module.exports = mongoose.model('Subscription', subscriptionSchema);