export function Index() {
  return (
    <div className="container mx-auto">
      <div className="text-[#353535] text-[18px]">
        <section className="">
          <div>
            <p className="text-[#000] text-[35px] font-semibold text-center">
              Privacy Policy
            </p>
            <p className="text-[#000] text-[18px] mb-6">
              <span className="text-[#000] font-semibold">Effective date:</span>{" "}
              6th December 2023
            </p>
            <p className="text-[#353535] text-[18px] mb-2">
              Welcome to AVBIDS!{" "}
            </p>
            <p className="text-[#353535] text-[18px] mb-2">
              The AV Bids LLC (“Company”, “Avbids”, “us”, “we”, or “our”) owns
              and operates avbids.com (hereinafter referred to as “Service”).{" "}
            </p>
            <p className="mb-2">
              The Company’s Privacy Policy governs your visit to
              http://www.avbids.com/ and explains how we collect, manage, use,
              safeguard and disclose Personal Information that results from your
              use of our Service, which is subject to the privacy principles set
              out in US Privacy Act 1974 and general law intended to protect
              your privacy, as amended from time to time, and where relevant by
              the European Union General Data Protection Regulations (EU)
              2016/679 (the GDPR), California Privacy Protection Act (the
              CalOPPA) and California Consumer Privacy Act (the CCPA).
            </p>
            <p className="mb-2">
              We use your data to provide and improve Service. By using Service,
              you agree to the collection and use of information in accordance
              with this policy. Unless otherwise defined in this Privacy Policy,
              the terms used in this Privacy Policy have the same meanings as in
              our Terms and Conditions. Our Terms and Conditions (“Terms”)
              govern all use of our Service and together with the Privacy Policy
              constitutes your agreement with us (“Agreement”).
            </p>
            <p className="mb-4">
              Our Terms and Conditions (“Terms”) govern all use of our Service
              and together with the Privacy Policy constitutes your agreement
              with us (“Agreement”).
            </p>

            <p>Definitions</p>
            <ul>
              <li>
                Service means the avbids.Com website operated by av bids llc.
              </li>
              <li>
                Personal data means data about a living individual who can be
                identified from those data (or from those and other information
                either in our possession or likely to come into our possession).
              </li>
              <li>
                Usage data is data collected automatically either generated by
                the use of service or from service infrastructure itself (for
                example, the duration of a page visit).
              </li>
              <li>
                Cookies are small files stored on your device (computer or
                mobile device).
              </li>
              <li>
                Data controller means a natural or legal person who (either
                alone or jointly or in common with other persons) determines the
                purposes for which and the manner in which any personal data
                are, or are to be, processed. For the purpose of this privacy
                policy, we are a data controller of your data.
              </li>
              <li>
                Data processors (or service providers) means any natural or
                legal person who processes the data on behalf of the data
                controller. We may use the services of various service providers
                in order to process your data more effectively.
              </li>
              <li>
                Data subject is any living individual who is the subject of
                personal data.
              </li>
              <li>
                The user is the individual using our service. The user
                corresponds to the data subject, who is the subject of personal
                data.
              </li>
            </ul>

            <p>Types of Data Collected</p>
            <p>
              We collect several different types of information for various
              purposes to provide and improve our
            </p>

            <p>Personal Data</p>
            <p>
              While using our Service, we may ask you to provide us with certain
              personally identifiable information that can be used to contact or
              identify you (“Personal Data”). Personally, identifiable
              information may include, but is not limited to:
            </p>

            <ul>
              <li>Email address</li>
              <li>className and SurclassName</li>
              <li>Business information</li>
              <li>Address</li>
              <li>Phone number Cookies and Usage Data</li>
            </ul>

            <p>
              We may use your Personal Data to contact you with newsletters,
              marketing or promotional materials and other information that may
              be of interest to you.
            </p>
            <p>
              You may opt out of receiving any, or all, of these communications
              from us by contacting us info@avbids.com
            </p>

            <p>Usage Data</p>
            <p>
              We may also collect information that your browser sends whenever
              you visit our Service or when you access Service by or through a
              mobile device (“Usage Data”).
            </p>
            <p>
              This Usage Data may include information such as your computer's
              Internet Protocol address (e.g., IP address), browser type,
              browser version, the pages of our Service that you visit, the time
              and date of your visit, the time spent on those pages, unique
              device identifiers and other diagnostic data.
            </p>
            <p>
              When you access Service with a mobile device, this Usage Data may
              include information such as the type of mobile device you use,
              your mobile device unique ID, the IP address of your mobile
              device, your mobile operating system, the type of mobile Internet
              browser you use, unique device identifiers and other diagnostic
              data.
            </p>

            <p>Device Information</p>
            <p>
              We collect device-specific information when you access our
              Services, including your hardware model, operating system and
              version, unique device identifiers, mobile network information,
              and information about the device’s interaction with our Services.
            </p>

            <div>
              <h2>Use of Data</h2>

              <div>
                <p>To provide and maintain our Service;</p>
                <p>To notify you about changes to our Service;</p>
                <p>
                  To allow you to participate in interactive features of our
                  Service when you choose to do so;
                </p>
                <p>To provide customer support;</p>
                <p>
                  To gather analysis or valuable information so that we can
                  improve our Service;
                </p>
                <p>To monitor the usage of our Service;</p>
                <p>To detect, prevent and address technical issues;</p>
                <p>To fulfill any other purpose for which you provide it;</p>
                <p>
                  To carry out our obligations and enforce our rights arising
                  from any contracts entered into between you and us, including
                  for billing and collection;
                </p>
                <p>
                  To provide you with notices about your account and/or
                  subscription, including expiration and renewal notices,
                  email-instructions, etc.;
                </p>
                <p>
                  To provide you with news, special offers, and general
                  information about other goods, services, and events which we
                  offer that are similar to those that you have already
                  purchased or inquired about unless you have opted not to
                  receive such information;
                </p>
                <p>
                  In any other way we may describe when you provide the
                  information;
                </p>
                <p>For any other purpose with your consent.</p>
              </div>
            </div>

            <div>
              <p>Retention of Data</p>
              <p>
                We will retain your Personal Data only for as long as is
                necessary for the purposes set out in this Privacy Policy.
              </p>

              <p>
                We will retain and use your Personal Data to the extent
                necessary to comply with our legal obligations (for example, if
                we are required to retain your data to comply with applicable
                laws), resolve disputes, and enforce our legal agreements and
                policies.
              </p>

              <p>
                We will also retain Usage Data for internal analysis purposes.
              </p>

              <p>
                Usage Data is generally retained for a shorter period, except
                when this data is used to strengthen the security or to improve
                the functionality of our Service, or we are legally obligated to
                retain this data for longer time periods.
              </p>
            </div>

            <div>
              <p>Transfer of data</p>
              <p>
                Your information, including Personal Data, may be transferred to
                – and maintained on – computers located outside of your state,
                province, country or other governmental jurisdiction where the
                data protection laws may differ from those of your jurisdiction.
              </p>
              <p>
                If you are located outside the United States Islands and choose
                to provide information to us, please note that we transfer the
                data, including Personal Data, to the United States Islands and
                process it there.
              </p>
              <p>
                Your consent to this Privacy Policy followed by your submission
                of such information represents your agreement to that transfer.
              </p>
              <p>
                The Company will take all the steps reasonably necessary to
                ensure that your data is treated securely and in accordance with
                this Privacy Policy and no transfer of your Personal Data will
                take place to an organization or a country unless there are
                adequate controls in place including the security of your data
                and other personal information.
              </p>
            </div>

            <div>
              <h2>Data Disclosure</h2>

              <h3>Disclosure for Law Enforcement</h3>
              <p>
                Under certain circumstances, we may be required to disclose your
                Personal Data if required to do so by law or in response to
                valid requests by public authorities.
              </p>

              <h3>Business Transaction</h3>
              <p>
                If we or our subsidiaries are involved in a merger, acquisition
                or asset sale, your Personal Data may be transferred.
              </p>

              <h3>Other Cases</h3>
              <ul>
                <li>We may disclose your information also</li>
                <li>to our subsidiaries and affiliates</li>
                <li>
                  to contractors, service providers, and other third parties we
                  use to support our business;
                </li>
                <li>to fulfill the purpose for which you provide it;</li>
                <li>
                  for the purpose of including your company’s logo on our
                  website;
                </li>
                <li>
                  for any other purpose disclosed by us when you provide the
                  information;
                </li>
                <li>with your consent in any other cases;</li>
                <li>
                  if we believe disclosure is necessary or appropriate to
                  protect the rights, property, or safety of the Company, our
                  customers, or others.
                </li>
              </ul>
            </div>
            <div>
              <p>Security of Data</p>
              <p>
                The security of your data is important to us but remember that
                no method of transmission over the Internet or method of
                electronic storage is 100% secure.
              </p>
              <p>
                . While we strive to use commercially acceptable means to
                protect your Personal Data, we cannot guarantee its absolute
                security.
              </p>
            </div>

            <div>
              <h2>Your Rights</h2>
              <p>You have the following rights in relation to your Data:</p>
              <ul>
                <li>
                  <strong>Right to access</strong> - the right to request (i)
                  copies of the information we hold about you at any time, or
                  (ii) that we modify, update or delete such information. If we
                  provide you with access to the information, we hold about you,
                  we will not charge you for this unless your request is
                  "manifestly unfounded or excessive." Where we are legally
                  permitted to do so, we may refuse your request. If we refuse
                  your request, we will tell you the reasons why.
                </li>
                <li>
                  <strong>Right to correct</strong> - the right to have your
                  Data rectified if it is inaccurate or incomplete.
                </li>
                <li>
                  <strong>Right to erase</strong> - the right to request that we
                  delete or remove your Data from our systems.
                </li>
                <li>
                  <strong>Right to restrict our use of your Data</strong> - the
                  right to "block" us from using your Data or limit the way in
                  which we can use it.
                </li>
                <li>
                  <strong>Right to data portability</strong> - the right to
                  request that we move, copy, or transfer your Data.
                </li>
                <li>
                  <strong>Right to object</strong> - the right to object to our
                  use of your Data, including where we use it for our legitimate
                  interests.
                </li>
              </ul>
              <p>
                To make enquiries, exercise any of your rights set out above, or
                withdraw your consent to the processing of your Data (where
                consent is our legal basis for processing your Data), please
                contact us via this e-mail address:{" "}
                <a href="mailto:info@avbids.com">info@avbids.com</a>
              </p>
              <p>
                If you are not satisfied with the way a complaint you make in
                relation to your Data is handled by us, you may be able to refer
                your complaint to the relevant data protection authority.
              </p>
              <p>
                It is important that the Data we hold about you is accurate and
                current. Please keep us informed if your Data changes during the
                period for which we hold it.
              </p>
            </div>

            <div>
              <p>
                Your Data Protection Rights Under General Data Protection
                Regulation (GDPR)
              </p>
              <p>
                If you are a resident of the European Union (EU) and European
                Economic Area (EEA), you have certain data protection rights,
                covered by GDPR. – See more at{" "}
                <a href="https://eurlex.europa.eu/eli/reg/2016/679/oj">
                  https://eurlex.europa.eu/eli/reg/2016/679/oj
                </a>
              </p>
              <p>
                We aim to take reasonable steps to allow you to correct, amend,
                delete, or limit the use of your Personal Data.
              </p>
              <p>
                If you wish to be informed what Personal Data, we hold about you
                and if you want it to be removed from our systems, please email
                us at <a href="mailto:info@avbids.com">info@avbids.com</a>
              </p>
              <p>
                In certain circumstances, you have the following data protection
                rights:
              </p>
              <ul>
                <li>
                  the right to access, update or to delete the information we
                  have on you
                </li>
                <li>
                  the right of rectification. You have the right to have your
                  information rectified if that information is inaccurate or
                  incomplete;
                </li>
                <li>
                  the right to object. You have the right to object to our
                  processing of your Personal Data;
                </li>
                <li>
                  the right of restriction. You have the right to request that
                  we restrict the processing of your personal information;
                </li>
                <li>
                  the right to data portability. You have the right to be
                  provided with a copy of your Personal Data in a structured,
                  machine-readable and commonly used format;
                </li>
                <li>
                  the right to withdraw consent. You also have the right to
                  withdraw your consent at any time where we rely on your
                  consent to process your personal information;
                </li>
              </ul>
              <p>
                Please note that we may ask you to verify your identity before
                responding to such requests. Please note, we may not be able to
                provide Service without some necessary data.
              </p>
              <p>
                You have the right to complain to a Data Protection Authority
                about our collection and use of your Personal Data. For more
                information, please contact your local data protection authority
                in the European Economic Area (EEA).
              </p>
            </div>

            <div>
              <h2>
                Your Data Protection Rights under the California Privacy
                Protection Act (CalOPPA)
              </h2>
              <p>
                CalOPPA is the first state law in the nation to require
                commercial websites and online services to post a privacy
                policy...
              </p>

              <h3>According to CalOPPA we agree to the following:</h3>
              <ul>
                <li>Users can visit our site anonymously.</li>
                <li>
                  Our Privacy Policy link includes the word “Privacy” and can
                  easily be found on the page specified above on the home page
                  of our website.
                </li>
                <li>
                  Users will be notified of any privacy policy changes on our
                  Privacy Policy Page.
                </li>
                <li>
                  Users are able to change their personal information by
                  emailing us at{" "}
                  <a href="mailto:info@avbids.com">info@avbids.com</a>.
                </li>
              </ul>

              <h3>Our Policy on “Do Not Track” Signals:</h3>
              <p>
                We honor Do Not Track signals and do not track, plant cookies,
                or use advertising when a Do Not Track browser mechanism is in
                place. Do Not Track is a preference you can set in your web
                browser to inform websites that you do not want to be tracked.
              </p>
              <p>
                You can enable or disable Do Not Track by visiting the
                Preferences or Settings page of your web browser.
              </p>
            </div>

            <div>
              <h1>
                Your Data Protection Rights under the California Consumer
                Privacy Act (CCPA)
              </h1>
              <p>
                If you are a California resident, you are entitled to learn what
                data we collect about you, ask to delete your data and not to
                sell (share) it. To exercise your data protection rights, you
                can make certain requests and ask us:
              </p>

              <ul>
                <li>
                  <strong>What personal information we have about you</strong>
                  <ul>
                    <li>
                      The categories of personal information we have collected
                      about you
                    </li>
                    <li>
                      The categories of sources from which we collect your
                      personal information.
                    </li>
                    <li>
                      The business or commercial purpose for collecting or
                      selling your personal information.
                    </li>
                    <li>
                      The categories of third parties with whom we share
                      personal information.
                    </li>
                    <li>
                      The specific pieces of personal information we have
                      collected about you.
                    </li>
                    <li>
                      A list of categories of personal information that we have
                      sold, along with the category of any other company we sold
                      it to. If we have not sold your personal information, we
                      will inform you of that fact.
                    </li>
                    <li>
                      A list of categories of personal information that we have
                      disclosed for a business purpose, along with the category
                      of any other company we shared it with.
                    </li>
                  </ul>
                </li>
                <li>
                  Please note, you are entitled to ask us to provide you with
                  this information up to two times in a rolling twelve-month
                  period. When you make this request, the information provided
                  may be limited to the personal information we collected about
                  you in the previous 12 months.
                </li>
                <li>
                  <strong>To delete your personal information</strong>
                  <ul>
                    <li>
                      If you make this request, we will delete the personal
                      information we hold about you as of the date of your
                      request from our records and direct any service providers
                      to do the same. In some cases, deletion may be
                      accomplished through deidentification of the information.
                      If you choose to delete your personal information, you may
                      not be able to use certain functions that require your
                      personal information to operate.
                    </li>
                  </ul>
                </li>
                <li>
                  <strong>To stop selling your personal information</strong>
                  <ul>
                    <li>
                      We don't sell or rent your personal information to any
                      third parties for any purpose. You are the only owner of
                      your Personal Data and can request disclosure or deletion
                      at any time.
                    </li>
                  </ul>
                </li>
              </ul>
            </div>

            <div>
              <p>
                Please note, if you ask us to delete or stop selling your data,
                it may impact your experience with us, and you may not be able
                to participate in certain programs or membership services which
                require the usage of your personal information to function. But
                in no circumstances, we will discriminate against you for
                exercising your rights.
              </p>

              <p>
                To exercise your California data protection rights described
                above, please send your request(s) by one of the following
                means:
              </p>

              <ul>
                <li>
                  By email: <a href="mailto:info@avbids.com">info@avbids.com</a>
                </li>
              </ul>

              <p>
                Your data protection rights, described above, are covered by the
                CCPA, short for the California Consumer Privacy Act. To find out
                more, visit the official California Legislative Information
                website. The CCPA took effect on 01/01/2020.
              </p>
            </div>

            <div>
              <p>
                We may employ third party companies and individuals to
                facilitate our Service (“Service Providers”), provide Service on
                our behalf, perform Service-related services or assist us in
                analyzing how our Service is used.
              </p>
              <p>
                These third parties have access to your Personal Data only to
                perform these tasks on our behalf and are obligated not to
                disclose or use it for any other purpose.
              </p>
            </div>

            <div>
              <h2>Payments</h2>
              <p>
                We may provide paid products and/or services within the Service.
                In that case, we use third-party services for payment processing
                (e.g., payment processors).
              </p>

              <p>
                <strong>
                  14.2. We will not store or collect your payment card details.
                </strong>{" "}
                That information is provided directly to our third-party payment
                processors whose use of your personal information is governed by
                their Privacy Policy. These payment processors adhere to the
                standards set by PCI-DSS as managed by the PCI Security
                Standards Council, which is a joint effort of brands like Visa,
                Mastercard, American Express, and Discover. PCI-DSS requirements
                help ensure the secure handling of payment information.
              </p>

              <p>
                <strong>The payment processors we may work with are:</strong>
              </p>
              <ul>
                <li>
                  Stripe
                  <p>
                    Their Privacy Policy can be viewed at:{" "}
                    <a href="https://stripe.com/us/privacy" target="_blank">
                      https://stripe.com/us/privacy
                    </a>
                  </p>
                </li>
              </ul>
            </div>

            <div>
              <p>Links To Other Sites</p>
              <p>
                Our Service may contain links to other sites that are not
                operated by us.
              </p>
              <p>
                If you click a third-party link, you will be directed to that
                third party's site.
              </p>
              <p>
                We strongly advise you to review the Privacy Policy of every
                site you visit.
              </p>
              <p>
                We have no control over and assume no responsibility for the
                content, privacy policies or practices of any third-party sites
                or services.
              </p>
            </div>

            <div>
              <h2>Children’s Privacy</h2>
              <p>
                Our Services are not intended for use by children under the age
                of 13 (“Children”).
              </p>
              <p>
                We do not knowingly collect personally identifiable information
                from Children under 13.
              </p>
              <p>
                If you become aware that a Child has provided us with Personal
                Data, pleasecontact us.
              </p>
              <p>
                If you become aware that a Child has provided us with Personal
                Data, pleasecontact us.
              </p>

              <p>
                If we become aware that we have collected Personal Data from
                Children without verification of parental consent, we take steps
                to remove that information from our servers.
              </p>
            </div>

            <div>
              <p>Changes to this Privacy Policy</p>
              <p>
                We may update our Privacy Policy from time to time. We will
                notify you of any changes by posting the new Privacy Policy on
                this page
              </p>
              <p>
                We will let you know via email and/or a prominent notice on our
                Service, prior to the change becoming effective and update
                “effective date” at the top of this Privacy Policy.
              </p>
              <p>
                You are advised to review this Privacy Policy periodically for
                any changes. Changes to this Privacy Policy are effective when
                they are posted on this page.
              </p>

              <div>
                <p>Contact Us</p>
                <p>
                  If you have any questions about this Privacy Policy, please
                  contact us:
                </p>
                <p>By email: info@avbids.com</p>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}

export default Index;
