export function Index() {
  return (
    <div className="container mx-auto">
      <div className="text-[#353535] text-[18px]">
        <section className="">
          <div>
            <p className="text-[#000] text-[35px] font-semibold text-center">
              Privacy Policy
            </p>
            <p className="text-[#000] text-[18px] mb-6">
              <span className="text-[#000] font-semibold">Effective date:</span>{" "}
              6th December 2023
            </p>
            <p className="text-[#353535] text-[18px] mb-4">
              Welcome to AVBIDS!{" "}
            </p>
            <p className="text-[#353535] text-[18px] mb-4">
              The AV Bids LLC (“Company”, “Avbids”, “us”, “we”, or “our”) owns
              and operates avbids.com (hereinafter referred to as “Service”).{" "}
            </p>
            <p className="mb-4">
              The Company’s Privacy Policy governs your visit to
              http://www.avbids.com/ and explains how we collect, manage, use,
              safeguard and disclose Personal Information that results from your
              use of our Service, which is subject to the privacy principles set
              out in US Privacy Act 1974 and general law intended to protect
              your privacy, as amended from time to time, and where relevant by
              the European Union General Data Protection Regulations (EU)
              2016/679 (the GDPR), California Privacy Protection Act (the
              CalOPPA) and California Consumer Privacy Act (the CCPA).
            </p>
            <p className="mb-4">
              We use your data to provide and improve Service. By using Service,
              you agree to the collection and use of information in accordance
              with this policy. Unless otherwise defined in this Privacy Policy,
              the terms used in this Privacy Policy have the same meanings as in
              our Terms and Conditions. Our Terms and Conditions (“Terms”)
              govern all use of our Service and together with the Privacy Policy
              constitutes your agreement with us (“Agreement”).
            </p>
            <p className="mb-6">
              Our Terms and Conditions (“Terms”) govern all use of our Service
              and together with the Privacy Policy constitutes your agreement
              with us (“Agreement”).
            </p>

            <ol className="list-decimal">
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold">Definitions</li>

              <ul className="list-disc mb-8">
                <li>
                  <span className="text-[#000] font-bold">Service </span>
                  means the avbids.Com website operated by av bids llc.
                </li>
                <li>
                  <span className="text-[#000] font-bold">Personal data </span>
                  means data about a living individual who can be identified
                  from those data (or from those and other information either in
                  our possession or likely to come into our possession).
                </li>
                <li>
                  <span className="text-[#000] font-bold">Usage data </span>
                  is data collected automatically either generated by the use of
                  service or from service infrastructure itself (for example,
                  the duration of a page visit).
                </li>
                <li>
                  <span className="text-[#000] font-bold">Cookies </span>
                  are small files stored on your device (computer or mobile
                  device).
                </li>
                <li>
                  <span className="text-[#000] font-bold">
                    Data controller{" "}
                  </span>
                  means a natural or legal person who (either alone or jointly
                  or in common with other persons) determines the purposes for
                  which and the manner in which any personal data are, or are to
                  be, processed. For the purpose of this privacy policy, we are
                  a data controller of your data.
                </li>
                <li>
                  <span className="text-[#000] font-bold">
                    Data processors (or service providers){" "}
                  </span>
                  means any natural or legal person who processes the data on
                  behalf of the data controller. We may use the services of
                  various service providers in order to process your data more
                  effectively.
                </li>
                <li>
                  <span className="text-[#000] font-bold"> Data subject </span>
                  is any living individual who is the subject of personal data.
                </li>
                <li>
                  <span className="text-[#000] font-bold">The user </span>
                  is the individual using our service. The user corresponds to
                  the data subject, who is the subject of personal data.
                </li>
              </ul>
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}

              <li className="text-[25px] text-[#000] font-bold">
                Types of Data Collected
              </li>
              <p className="mb-4">
                We collect several different types of information for various
                purposes to provide and improve our
              </p>

              <p className="mb-4 text-[22px] font-bold">Personal Data</p>
              <p className="mb-4">
                While using our Service, we may ask you to provide us with
                certain personally identifiable information that can be used to
                contact or identify you (“Personal Data”). Personally,
                identifiable information may include, but is not limited to:
              </p>

              <ul className="mb-4 list-disc">
                <li>Email address</li>
                <li>className and SurclassName</li>
                <li>Business information</li>
                <li>Address</li>
                <li>Phone number Cookies and Usage Data</li>
              </ul>

              <p className="mb-4">
                We may use your Personal Data to contact you with newsletters,
                marketing or promotional materials and other information that
                may be of interest to you.
              </p>
              <p className="mb-4">
                You may opt out of receiving any, or all, of these
                communications from us by contacting us info@avbids.com
              </p>

              <p className="mb-4">Usage Data</p>
              <p className="mb-4">
                We may also collect information that your browser sends whenever
                you visit our Service or when you access Service by or through a
                mobile device (“Usage Data”).
              </p>
              <p className="mb-4">
                This Usage Data may include information such as your computer's
                Internet Protocol address (e.g., IP address), browser type,
                browser version, the pages of our Service that you visit, the
                time and date of your visit, the time spent on those pages,
                unique device identifiers and other diagnostic data.
              </p>
              <p className="mb-4">
                When you access Service with a mobile device, this Usage Data
                may include information such as the type of mobile device you
                use, your mobile device unique ID, the IP address of your mobile
                device, your mobile operating system, the type of mobile
                Internet browser you use, unique device identifiers and other
                diagnostic data.
              </p>

              <p className="mb-4">Device Information</p>
              <p className="mb-4">
                We collect device-specific information when you access our
                Services, including your hardware model, operating system and
                version, unique device identifiers, mobile network information,
                and information about the device’s interaction with our
                Services.
              </p>

              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold">Use of Data</li>
              <div className="mb-4">
                <div className="mb-4">
                  <p className="mb-4">To provide and maintain our Service;</p>
                  <p className="mb-4">
                    To notify you about changes to our Service;
                  </p>
                  <p className="mb-4">
                    To allow you to participate in interactive features of our
                    Service when you choose to do so;
                  </p>
                  <p className="mb-4">To provide customer support;</p>
                  <p className="mb-4">
                    To gather analysis or valuable information so that we can
                    improve our Service;
                  </p>
                  <p className="mb-4">To monitor the usage of our Service;</p>
                  <p className="mb-4">
                    To detect, prevent and address technical issues;
                  </p>
                  <p className="mb-4">
                    To fulfill any other purpose for which you provide it;
                  </p>
                  <p className="mb-4">
                    To carry out our obligations and enforce our rights arising
                    from any contracts entered into between you and us,
                    including for billing and collection;
                  </p>
                  <p className="mb-4">
                    To provide you with notices about your account and/or
                    subscription, including expiration and renewal notices,
                    email-instructions, etc.;
                  </p>
                  <p className="mb-4">
                    To provide you with news, special offers, and general
                    information about other goods, services, and events which we
                    offer that are similar to those that you have already
                    purchased or inquired about unless you have opted not to
                    receive such information;
                  </p>
                  <p className="mb-4">
                    In any other way we may describe when you provide the
                    information;
                  </p>
                  <p className="mb-4">
                    For any other purpose with your consent.
                  </p>
                </div>
              </div>

              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold">
                Retention of Data
              </li>

              <div className="mb-4">
                <p className="mb-4">
                  We will retain your Personal Data only for as long as is
                  necessary for the purposes set out in this Privacy Policy.
                </p>

                <p className="mb-4">
                  We will retain and use your Personal Data to the extent
                  necessary to comply with our legal obligations (for example,
                  if we are required to retain your data to comply with
                  applicable laws), resolve disputes, and enforce our legal
                  agreements and policies.
                </p>

                <p className="mb-4">
                  We will also retain Usage Data for internal analysis purposes.
                </p>

                <p className="mb-4">
                  Usage Data is generally retained for a shorter period, except
                  when this data is used to strengthen the security or to
                  improve the functionality of our Service, or we are legally
                  obligated to retain this data for longer time periods.
                </p>
              </div>
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold">
                Transfer of Data
              </li>

              <div className="mb-4">
                <p className="mb-4">
                  Your information, including Personal Data, may be transferred
                  to – and maintained on – computers located outside of your
                  state, province, country or other governmental jurisdiction
                  where the data protection laws may differ from those of your
                  jurisdiction.
                </p>
                <p className="mb-4">
                  If you are located outside the United States Islands and
                  choose to provide information to us, please note that we
                  transfer the data, including Personal Data, to the United
                  States Islands and process it there.
                </p>
                <p className="mb-4">
                  Your consent to this Privacy Policy followed by your
                  submission of such information represents your agreement to
                  that transfer.
                </p>
                <p className="mb-4">
                  The Company will take all the steps reasonably necessary to
                  ensure that your data is treated securely and in accordance
                  with this Privacy Policy and no transfer of your Personal Data
                  will take place to an organization or a country unless there
                  are adequate controls in place including the security of your
                  data and other personal information.
                </p>
              </div>
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold">
                Disclosure of Data
              </li>

              <div className="mb-4">
                <h3 className="mb-4">Disclosure for Law Enforcement</h3>
                <p className="mb-4">
                  Under certain circumstances, we may be required to disclose
                  your Personal Data if required to do so by law or in response
                  to valid requests by public authorities.
                </p>

                <h3 className="mb-4">Business Transaction</h3>
                <p>
                  If we or our subsidiaries are involved in a merger,
                  acquisition or asset sale, your Personal Data may be
                  transferred.
                </p>

                <h3 className="mb-4">Other Cases</h3>
                <ul className="mb-4">
                  <li>We may disclose your information also</li>
                  <li>to our subsidiaries and affiliates</li>
                  <li>
                    to contractors, service providers, and other third parties
                    we use to support our business;
                  </li>
                  <li>to fulfill the purpose for which you provide it;</li>
                  <li>
                    for the purpose of including your company’s logo on our
                    website;
                  </li>
                  <li>
                    for any other purpose disclosed by us when you provide the
                    information;
                  </li>
                  <li>with your consent in any other cases;</li>
                  <li>
                    if we believe disclosure is necessary or appropriate to
                    protect the rights, property, or safety of the Company, our
                    customers, or others.
                  </li>
                </ul>
              </div>
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold">
                Security of Data
              </li>

              <div className="mb-4">
                <p className="mb-4">
                  The security of your data is important to us but remember that
                  no method of transmission over the Internet or method of
                  electronic storage is 100% secure.
                </p>
                <p className="mb-4">
                  . While we strive to use commercially acceptable means to
                  protect your Personal Data, we cannot guarantee its absolute
                  security.
                </p>
              </div>
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold">Your Rights</li>
              <div className="mb-4">
                <p className="mb-4">
                  You have the following rights in relation to your Data:
                </p>
                <ul className="mb-4">
                  <li>
                    <strong>Right to access</strong> - the right to request (i)
                    copies of the information we hold about you at any time, or
                    (ii) that we modify, update or delete such information. If
                    we provide you with access to the information, we hold about
                    you, we will not charge you for this unless your request is
                    "manifestly unfounded or excessive." Where we are legally
                    permitted to do so, we may refuse your request. If we refuse
                    your request, we will tell you the reasons why.
                  </li>
                  <li>
                    <strong>Right to correct</strong> - the right to have your
                    Data rectified if it is inaccurate or incomplete.
                  </li>
                  <li>
                    <strong>Right to erase</strong> - the right to request that
                    we delete or remove your Data from our systems.
                  </li>
                  <li>
                    <strong>Right to restrict our use of your Data</strong> -
                    the right to "block" us from using your Data or limit the
                    way in which we can use it.
                  </li>
                  <li>
                    <strong>Right to data portability</strong> - the right to
                    request that we move, copy, or transfer your Data.
                  </li>
                  <li>
                    <strong>Right to object</strong> - the right to object to
                    our use of your Data, including where we use it for our
                    legitimate interests.
                  </li>
                </ul>
                <p className="mb-4">
                  To make enquiries, exercise any of your rights set out above,
                  or withdraw your consent to the processing of your Data (where
                  consent is our legal basis for processing your Data), please
                  contact us via this e-mail address:{" "}
                  <a href="mailto:info@avbids.com">info@avbids.com</a>
                </p>
                <p className="mb-4">
                  If you are not satisfied with the way a complaint you make in
                  relation to your Data is handled by us, you may be able to
                  refer your complaint to the relevant data protection
                  authority.
                </p>
                <p className="mb-4">
                  It is important that the Data we hold about you is accurate
                  and current. Please keep us informed if your Data changes
                  during the period for which we hold it.
                </p>
              </div>
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold">
                Your Data Protection Rights Under General Data Protection
                Regulation (GDPR)
              </li>
              <div className="mb-4">
                <p className="mb-4">
                  If you are a resident of the European Union (EU) and European
                  Economic Area (EEA), you have certain data protection rights,
                  covered by GDPR. – See more at{" "}
                  <a href="https://eurlex.europa.eu/eli/reg/2016/679/oj">
                    https://eurlex.europa.eu/eli/reg/2016/679/oj
                  </a>
                </p>
                <p className="mb-4">
                  We aim to take reasonable steps to allow you to correct,
                  amend, delete, or limit the use of your Personal Data.
                </p>
                <p className="mb-4">
                  If you wish to be informed what Personal Data, we hold about
                  you and if you want it to be removed from our systems, please
                  email us at{" "}
                  <a href="mailto:info@avbids.com">info@avbids.com</a>
                </p>
                <p className="mb-4">
                  In certain circumstances, you have the following data
                  protection rights:
                </p>
                <ul className="mb-4">
                  <li>
                    the right to access, update or to delete the information we
                    have on you
                  </li>
                  <li>
                    the right of rectification. You have the right to have your
                    information rectified if that information is inaccurate or
                    incomplete;
                  </li>
                  <li>
                    the right to object. You have the right to object to our
                    processing of your Personal Data;
                  </li>
                  <li>
                    the right of restriction. You have the right to request that
                    we restrict the processing of your personal information;
                  </li>
                  <li>
                    the right to data portability. You have the right to be
                    provided with a copy of your Personal Data in a structured,
                    machine-readable and commonly used format;
                  </li>
                  <li>
                    the right to withdraw consent. You also have the right to
                    withdraw your consent at any time where we rely on your
                    consent to process your personal information;
                  </li>
                </ul>
                <p className="mb-4">
                  Please note that we may ask you to verify your identity before
                  responding to such requests. Please note, we may not be able
                  to provide Service without some necessary data.
                </p>
                <p className="mb-4">
                  You have the right to complain to a Data Protection Authority
                  about our collection and use of your Personal Data. For more
                  information, please contact your local data protection
                  authority in the European Economic Area (EEA).
                </p>
              </div>
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold mb-4">
                Your Data Protection Rights under the California Privacy
                Protection Act (CalOPPA)
              </li>
              <div className="mb-4">
                <p className="mb-4">
                  CalOPPA is the first state law in the nation to require
                  commercial websites and online services to post a privacy
                  policy. The law’s reach stretches well beyond California to
                  require a person or company in the United States (and
                  conceivable the world) that operates websites collecting
                  personally identifiable information from California consumers
                  to post a conspicuous privacy policy on its website stating
                  exactly the information being collected and those individuals
                  with whom it is being shared, and to comply with this policy.
                  – See more at:{" "}
                  <a
                    href="mailto:info@avbids.com"
                    className="text-[#5912FF] underline"
                  >
                    {" "}
                    https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protectionact-caloppa-3/
                  </a>
                </p>

                <p className="mb-4">
                  According to CalOPPA we agree to the following:
                </p>

                <ul className="list-disc">
                  <li>Users can visit our site anonymously.</li>
                  <li>
                    Our Privacy Policy link includes the word “Privacy” and can
                    easily be found on the page specified above on the home page
                    of our website.
                  </li>
                  <li>
                    Users will be notified of any privacy policy changes on our
                    Privacy Policy Page.
                  </li>
                  <li>
                    Users are able to change their personal information by
                    emailing us at{" "}
                    <a href="mailto:info@avbids.com">info@avbids.com</a>.
                  </li>

                  <li className="mb-4">
                    Our Policy on “Do Not Track” Signals:
                  </li>
                </ul>

                <p className="mb-4">
                  We honor Do Not Track signals and do not track, plant cookies,
                  or use advertising when a Do Not Track browser mechanism is in
                  place. Do Not Track is a preference you can set in your web
                  browser to inform websites that you do not want to be tracked.
                </p>
                <p className="mb-4">
                  You can enable or disable Do Not Track by visiting the
                  Preferences or Settings page of your web browser.
                </p>
              </div>
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold mb-4">
                Your Data Protection Rights under the California Consumer
                Privacy Act (CCPA)
              </li>
              <div className="mb-4">
                <p className="mb-4">
                  If you are a California resident, you are entitled to learn
                  what data we collect about you, ask to delete your data and
                  not to sell (share) it. To exercise your data protection
                  rights, you can make certain requests and ask us:
                </p>
                <p className="text-[22px] text-[#000] font-bold mb-4">
                  What personal information we have about you
                </p>
                <p className="mb-4">
                  {" "}
                  If you make this request, we will return to you:
                </p>
                <ul className="list-disc mb-4">
                  <li>
                    The categories of personal information we have collected
                    about you
                  </li>
                  <li>
                    The categories of sources from which we collect your
                    personal information.
                  </li>
                  <li>
                    The business or commercial purpose for collecting or selling
                    your personal information.
                  </li>
                  <li>
                    The categories of third parties with whom we share personal
                    information.
                  </li>
                  <li>
                    The specific pieces of personal information we have
                    collected about you.
                  </li>
                  <li>
                    A list of categories of personal information that we have
                    sold, along with the category of any other company we sold
                    it to. If we have not sold your personal information, we
                    will inform you of that fact.
                  </li>
                  <li>
                    A list of categories of personal information that we have
                    disclosed for a business purpose, along with the category of
                    any other company we shared it with.
                  </li>
                </ul>
                <p className="mb-4">
                  {" "}
                  Please note, you are entitled to ask us to provide you with
                  this information up to two times in a rolling twelve-month
                  period. When you make this request, the information provided
                  may be limited to the personal information we collected about
                  you in the previous 12 months.
                </p>
                <p className="text-[22px] text-[#000] mb-4 font-bold">
                  To delete your personal information
                </p>

                <p className="mb-4">
                  {" "}
                  If you make this request, we will delete the personal
                  information we hold about you as of the date of your request
                  from our records and direct any service providers to do the
                  same. In some cases, deletion may be accomplished through
                  deidentification of the information. If you choose to delete
                  your personal information, you may not be able to use certain
                  functions that require your personal information to operate.
                </p>

                <p className="text-[22px] text-[#000] mb-4 font-bold">
                  To stop selling your personal information
                </p>

                <p>
                  We don't sell or rent your personal information to any third
                  parties for any purpose. You are the only owner of your
                  Personal Data and can request disclosure or deletion at any
                  time.
                </p>
              </div>

              <div className="mb-4">
                <p className="mb-4">
                  Please note, if you ask us to delete or stop selling your
                  data, it may impact your experience with us, and you may not
                  be able to participate in certain programs or membership
                  services which require the usage of your personal information
                  to function. But in no circumstances, we will discriminate
                  against you for exercising your rights.
                </p>

                <p className="mb-4">
                  To exercise your California data protection rights described
                  above, please send your request(s) by one of the following
                  means:
                </p>

                <p className="mb-2">
                  {" "}
                  By email:{" "}
                  <a
                    href="mailto:info@avbids.com"
                    className="text-[#5912FF] underline"
                  >
                    info@avbids.com
                  </a>
                </p>

                <p className="mb-4">
                  Your data protection rights, described above, are covered by
                  the CCPA, short for the California Consumer Privacy Act. To
                  find out more, visit the official California Legislative
                  Information website. The CCPA took effect on 01/01/2020.
                </p>
              </div>
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold mb-4">
                Service Providers
              </li>

              <div className="mb-4">
                <p className="mb-4">
                  We may employ third party companies and individuals to
                  facilitate our Service{" "}
                  <span className="text-[#000] font-bold">
                    (“Service Providers”)
                  </span>
                  , provide Service on our behalf, perform Service-related
                  services or assist us in analyzing how our Service is used.
                </p>
                <p className="mb-4">
                  These third parties have access to your Personal Data only to
                  perform these tasks on our behalf and are obligated not to
                  disclose or use it for any other purpose.
                </p>
              </div>
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold mb-4">
                Payments
              </li>
              <div className="mb-4">
                <p className="mb-4">
                  We may provide paid products and/or services within the
                  Service. In that case, we use third-party services for payment
                  processing (e.g., payment processors).
                </p>

                <p className="mb-4">
                  services for payment processing (e.g. payment processors).
                  14.2. We will not store or collect your payment card details.
                  That information is provided directly to our third-party
                  payment processors whose use of your personal information is
                  governed by their Privacy Policy. These payment processors
                  adhere to the standards set by PCI-DSS as managed by the PCI
                  Security Standards Council, which is a joint effort of brands
                  like Visa, Mastercard, American Express and Discover. PCI-DSS
                  requirements help ensure the secure handling of payment
                  information.
                </p>

                <p className="mb-4">
                  The payment processors we may work with are:
                </p>

                <p className="mb-4 text-[22px] font-bold text-[#000]">Stripe</p>
                <p className="mb-4">
                  Their Privacy Policy can be viewed at:{" "}
                  <span className="text-[#5912FF] underline cursor-pointer">
                    {" "}
                    https://stripe.com/us/privacy
                  </span>
                </p>
              </div>
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold mb-4">
                Links To Other Sites
              </li>

              <div className="mb-4">
                <p className="mb-4">
                  Our Service may contain links to other sites that are not
                  operated by us.
                </p>
                <p className="mb-4">
                  If you click a third-party link, you will be directed to that
                  third party's site.
                </p>
                <p className="mb-4">
                  We strongly advise you to review the Privacy Policy of every
                  site you visit.
                </p>
                <p className="mb-4">
                  We have no control over and assume no responsibility for the
                  content, privacy policies or practices of any third-party
                  sites or services.
                </p>
              </div>
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold  mb-4">
                Children’s Privacy
              </li>

              <div className="mb-4">
                <p className="mb-4">
                  Our Services are not intended for use by children under the
                  age of 13 (“Children”).
                </p>
                <p className="mb-4">
                  We do not knowingly collect personally identifiable
                  information from Children under 13.
                </p>

                <p className="mb-4">
                  If you become aware that a Child has provided us with Personal
                  Data, pleasecontact us.
                </p>

                <p className="mb-4">
                  If we become aware that we have collected Personal Data from
                  Children without verification of parental consent, we take
                  steps to remove that information from our servers.
                </p>
              </div>
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold mb-4">
                Changes to this Privacy Policy
              </li>

              <p className="mb-4">
                We may update our Privacy Policy from time to time. We will
                notify you of any changes by posting the new Privacy Policy on
                this page
              </p>
              <p className="mb-4">
                We will let you know via email and/or a prominent notice on our
                Service, prior to the change becoming effective and update
                “effective date” at the top of this Privacy Policy.
              </p>
              <p className="mb-4">
                You are advised to review this Privacy Policy periodically for
                any changes. Changes to this Privacy Policy are effective when
                they are posted on this page.
              </p>
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
              <li className="text-[25px] text-[#000] font-bold mb-4">
                Contact Us
              </li>

              <div className="mb-4">
                <p className="mb-4">
                  If you have any questions about this Privacy Policy, please
                  contact us:
                </p>
                <p className="mb-4">By email: info@avbids.com</p>
              </div>
              {/* --------------------------------------------------------------------------------------------------------------------------------------------------------------- */}
            </ol>

            {/* <div className="mb-4">
              <h3 className="mb-4">Disclosure for Law Enforcement</h3>
              <p className="mb-4">
                Under certain circumstances, we may be required to disclose your
                Personal Data if required to do so by law or in response to
                valid requests by public authorities.
              </p>

              <h3 className="mb-4">Business Transaction</h3>
              <p>
                If we or our subsidiaries are involved in a merger, acquisition
                or asset sale, your Personal Data may be transferred.
              </p>

              <h3 className="mb-4">Other Cases</h3>
              <ul className="mb-4">
                <li>We may disclose your information also</li>
                <li>to our subsidiaries and affiliates</li>
                <li>
                  to contractors, service providers, and other third parties we
                  use to support our business;
                </li>
                <li>to fulfill the purpose for which you provide it;</li>
                <li>
                  for the purpose of including your company’s logo on our
                  website;
                </li>
                <li>
                  for any other purpose disclosed by us when you provide the
                  information;
                </li>
                <li>with your consent in any other cases;</li>
                <li>
                  if we believe disclosure is necessary or appropriate to
                  protect the rights, property, or safety of the Company, our
                  customers, or others.
                </li>
              </ul>
            </div> */}
          </div>
        </section>
      </div>
    </div>
  );
}

export default Index;
